language: objective-c
osx_image: xcode10

cache:
  directories:
    - Carthage
    - CookIslands/Carthage

env:
  #environment variables
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - PROJECT_NAME="MyProject.xcodeproj"
    - SCHEME_IOS_FRAMEWORK="MyFramework_iOS"
    - SCHEME_IOS="myAppScheme"
    - IOS_SDK=iphonesimulator12.0
  matrix:
    - DESTINATION="OS=12.0,name=iPhone X" SCHEME="$SCHEME_IOS" SDK="$IOS_SDK"

before_install:
  - carthage bootstrap
  - git submodule update --remote
  - gem install license_finder
  - carthage bootstrap --no-use-binaries --platform iOS
  - cd CookIslands && carthage bootstrap --no-use-binaries --platform iOS && cd ..

script:
  - xcodebuild test -project "$PROJECT_NAME" -scheme "$SCHEME" -destination "$DESTINATION" -sdk "$SDK" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

after_failure:
  - cat $TMPDIR/carthage-*.log 



language: objective-c
osx_image: xcode9.2


rvm:
- 2.2         #see before_install for getting RVM stable.

env:
- TRAVIS_TAG="1.0" PROJECT_NAME="UnityExamplePackage" UNITY_PROJECT_PATH="UnityExample" UNITY_DOWNLOAD_CACHE="$(pwd)/unity_download_cache" DEPLOY_UNITYPACKAGE="path set in deploy script"

cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

    
before_install:
- rvm get stable
- chmod a+x ./travis-build/*.sh

install:
- cat /etc/hosts
- ./travis-build/install-unity.sh

script:
- ./travis-build/build.sh
- ./travis-build/run-tests.sh

after_success:
- ./travis-build/export-unity-package.sh

before_deploy:
- DEPLOY_UNITYPACKAGE="$(ls -a release/*.zip | head -n 1)"



deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $DEPLOY_UNITYPACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true

